Update buildspec.yml
revamp

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -61,43 +61,43 @@ phases:
         echo $? > trufflehog_exit_code.txt
 
   post_build:
-  commands:
-    - echo "Uploading results to CSPM..."
-    - |
-      #!/bin/bash
-      # Check if results file exists
-      if [ ! -f trufflehog-results.json ]; then
-        echo "Error: trufflehog-results.json not found!"
-        exit 1
-      fi
+    commands:
+      - echo "Uploading results to CSPM..."
+      - |
+        #!/bin/bash
+        # Check if results file exists
+        if [ ! -f trufflehog-results.json ]; then
+          echo "Error: trufflehog-results.json not found!"
+          exit 1
+        fi
 
-      # Debug: Print CSPM URL and token
-      echo "CSPM_URL: $CSPM_URL"
-      echo "AK_TOKEN: ${AK_TOKEN}"
+        # Debug: Print CSPM URL and token
+        echo "CSPM_URL: $CSPM_URL"
+        echo "AK_TOKEN: ${AK_TOKEN}"
 
-      # Upload scan results
-      RESPONSE=$(curl --location --request POST "https://${CSPM_URL}/api/v1/artifact/?tenant_id=${TENANT_ID}&data_type=TruffleHog&save_to_s3=true&label_id=${LABEL}" \
-          --header "Tenant-Id: ${TENANT_ID}" \
-          --header "Authorization: Bearer ${AK_TOKEN}" \
-          --form "file=@$(pwd)/trufflehog-results.json")
-        echo "Response: $RESPONSE"
+        # Upload scan results
+        RESPONSE=$(curl --location --request POST "https://${CSPM_URL}/api/v1/artifact/?tenant_id=${TENANT_ID}&data_type=TruffleHog&save_to_s3=true&label_id=${LABEL}" \
+            --header "Tenant-Id: ${TENANT_ID}" \
+            --header "Authorization: Bearer ${AK_TOKEN}" \
+            --form "file=@$(pwd)/trufflehog-results.json")
+          echo "Response: $RESPONSE"
 
-      # Debug: Print curl response
-      echo "Curl Response: $RESPONSE"
+        # Debug: Print curl response
+        echo "Curl Response: $RESPONSE"
 
-      # Check upload response
-      if echo "$RESPONSE" | grep -q "File received successfully"; then
-        echo "Report uploaded successfully"
-      else
-        echo "Error uploading report: $RESPONSE"
-        exit 1
-      fi
+        # Check upload response
+        if echo "$RESPONSE" | grep -q "File received successfully"; then
+          echo "Report uploaded successfully"
+        else
+          echo "Error uploading report: $RESPONSE"
+          exit 1
+        fi
 
-      # Check TruffleHog exit code if FAIL is enabled
-      if [ "$FAIL" == "true" ] && [ $(cat trufflehog_exit_code.txt) -ne 0 ]; then
-        echo "Secrets detected! Failing build..."
-        exit 1
-      fi
+        # Check TruffleHog exit code if FAIL is enabled
+        if [ "$FAIL" == "true" ] && [ $(cat trufflehog_exit_code.txt) -ne 0 ]; then
+          echo "Secrets detected! Failing build..."
+          exit 1
+        fi
       
 artifacts:
   files:
